{{- if .Values.withSecretless }}
---
# This secret store the backend credentials
kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "demo-app-secretless.fullname" . }}-credentials"
type: Opaque
data:
  address:  {{ (required "A valid .Values.applicationDBAddress entry required!" .Values.applicationDBAddress) | b64enc | quote }}
  username: {{ (required "A valid .Values.applicationDBUsername entry required!" .Values.applicationDBUsername) | b64enc | quote }}
  password: {{ (required "A valid .Values.applicationDBPassword entry required!" .Values.applicationDBPassword) | b64enc | quote }}
{{- end }}
